import { company } from "./site";

export const reviewSla = "within 24 working hours of submission";

export const workflowStages = [
  { key: "SUBMITTED", label: "Submitted", description: `Your idea or request is received. We review ${reviewSla}.` },
  { key: "RESEARCH_REVIEW", label: "Under Review", description: "Verified or rejected. You are notified by email and in your portal." },
  { key: "APPROVED", label: "Agreed", description: "Next steps are sent to your email and remain visible in your portal." },
  { key: "FEASIBILITY_ANALYSIS", label: "Research", description: "Our team researches feasibility, scope, and delivery approach." },
  { key: "IN_DEVELOPMENT", label: "Development & Coding", description: "Research complete — our engineering team is building your solution." },
  { key: "REVIEW", label: "Presentation / Demo", description: "Delivery, pitching, or demo showcasing as agreed in your scope document." },
];

export const paymentPolicy = {
  channel: "M-Pesa Till — TechFlare Solutions (Till 9356451). This is our only payment method.",
  deposit: "60% deposit of the agreed amount before work begins",
  balance: "40% balance due at presentation, pitching, demo, or delivery of research reports and data (as applicable)",
  delays: "Late payment may reduce loyalty points and delay project timelines",
  refunds: "No refunds once an agreed scope document is signed by both parties",
  startCondition: "No work begins until a well-agreed document is confirmed by both TechFlare Solutions and the client/innovator",
  tillNumber: "9356451",
  tillName: "TechFlare Solutions",
};

export const termsSections = [
  {
    title: "1. Acceptance",
    body: `By using ${company.name} services, creating an account, or submitting ideas, solutions, or orders, you agree to these Terms and Conditions.`,
  },
  {
    title: "2. Account & Access",
    body: "Browsing is open to all visitors. Submitting ideas, solutions, community blog posts, AI tools, and portal actions requires a verified account. Google sign-in and email registration are supported.",
  },
  {
    title: "3. Submissions & Review",
    body: `Clients and innovators may submit ideas and work requests through the Innovation Hub, Solutions Center, or their portal. Each submission is verified or rejected ${reviewSla}. Outcomes are communicated by email and shown in your portal.`,
  },
  {
    title: "4. Agreed Scope & Invoices",
    body: "After approval, our team sends next steps by email. Invoices are generated by the Finance Office following an admin request. Each invoice includes a clear explanation of the work, deliverables, and timelines — visible in your client or innovator portal.",
  },
  {
    title: "5. Revisions",
    body: "Clients and innovators may request revisions easily through the portal. Requests are received by admin and forwarded to the development team. Revision history remains tracked in your portal.",
  },
  {
    title: "6. Workflow Transparency",
    body: "Your portal tracks project workflow — from research through development and coding — including status updates, milestone schedules, and percentage completion on the progress bar.",
  },
  {
    title: "7. Payment Policy",
    body: `${paymentPolicy.channel}. ${paymentPolicy.deposit}. ${paymentPolicy.balance}. ${paymentPolicy.delays}. ${paymentPolicy.refunds}. ${paymentPolicy.startCondition}.`,
  },
  {
    title: "8. Loyalty Points",
    body: company.pointsDescription,
  },
  {
    title: "9. Intellectual Property",
    body: "Idea and innovation submissions are subject to TechFlare's intellectual property review. Partnership and delivery terms are defined in individual agreed documents.",
  },
  {
    title: "10. Contact",
    body: `Questions: ${company.email} · ${company.phone}`,
  },
];

/** Full policy document for AI chatbot context */
export function buildPolicyDocument(): string {
  const workflow = workflowStages.map((s) => `- ${s.label}: ${s.description}`).join("\n");
  const terms = termsSections.map((s) => `${s.title}: ${s.body}`).join("\n");

  return `
TECHFLARE TERMS, WORKFLOW & PAYMENT POLICY (official document)

WORKFLOW PIPELINE:
${workflow}

PAYMENT POLICY:
- ${paymentPolicy.channel}
- ${paymentPolicy.deposit}
- ${paymentPolicy.balance}
- ${paymentPolicy.delays}
- ${paymentPolicy.refunds}
- ${paymentPolicy.startCondition}

TERMS & CONDITIONS:
${terms}
`.trim();
}
